FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    bash \
    findutils \
    imagemagick \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /bin

COPY --chmod=777 make_thumb_and_web_images.sh /bin/make_thumb_and_web_images.sh
