FROM elixir:1.18.2

# Build Args
ARG PHOENIX_VERSION=1.7.14

# Dependencies
RUN apt update \
  && apt upgrade -y \
  && apt install -y bash curl git build-essential inotify-tools

# App Directory
ENV APP_HOME /app
COPY ./app $APP_HOME
WORKDIR $APP_HOME

# Install Hex from GitHub instead of online builds.hex.pm
RUN mix local.hex --force

# Install Dependencies
RUN mix deps.get || mix deps.get
RUN mix assets.setup || true
RUN mix assets.build || true

# App Port
# EXPOSE 4000

# Default Command
CMD ["mix", "phx.server"]
