FROM elixir:1.18.2

# Build Args
ARG PHOENIX_VERSION=1.7.14

# Dependencies
RUN apt update \
  && apt upgrade -y \
  && apt install -y bash curl git build-essential inotify-tools

# App Directory
ENV APP_HOME /app
COPY ./app $APP_HOME
WORKDIR $APP_HOME

# set build ENV
ENV MIX_ENV="prod"

ARG ADMIN_USERNAME="admin"
ARG ADMIN_PASSWORD="admin"
ENV ADMIN_USERNAME=$ADMIN_USERNAME
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD

# install dependencies and compile assets
RUN mix deps.get
RUN mix assets.setup
RUN mix assets.deploy

# App Port
# EXPOSE 4000

# Default Command
CMD ["mix", "phx.server"]