services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
    # user: "1000:1000"
  db:
    image: postgres:17.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres