services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - ADMIN_USERNAME=admin
        - ADMIN_PASSWORD=admin
    ports:
      - "4000:4000"
    volumes:
      - uploads:/app/priv/static/uploads
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - DATABASE_URL=ecto://postgres:postgres@db/postgres
      - SECRET_KEY_BASE=zrMkg/peRCh4amd7hy2p5Eiost7aqpvmmZFoYFCwgxLiL120r6HvTrXUXT/8O36b
    depends_on:
      - db
    working_dir: /app
    command: bash -c "mix ecto.setup && mix phx.server"
    # user: "1000:1000"
  db:
    image: postgres:17.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - "database:/var/lib/postgresql/data"

volumes:
  database:
  uploads:
